from typing import List, Dict, Any

SAMPLE_LISTINGS: List[Dict[str, Any]] = [
    # Toyota
    {
        "make": "Toyota",
        "model": "Camry",
        "trim": "SE",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 28,
        "highway_mpg": 39,
    },
    {
        "make": "Toyota",
        "model": "Corolla",
        "trim": "LE",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 31,
        "highway_mpg": 40,
    },
    {
        "make": "Toyota",
        "model": "RAV4",
        "trim": "XLE",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 27,
        "highway_mpg": 35,
    },
    {
        "make": "Toyota",
        "model": "Highlander",
        "trim": "XLE",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 21,
        "highway_mpg": 29,
    },
    {
        "make": "Toyota",
        "model": "Prius",
        "trim": "Hybrid LE",
        "body_style": "Hatchback",
        "fuel_type": "Hybrid",
        "city_mpg": 54,
        "highway_mpg": 50,
    },

    # Honda
    {
        "make": "Honda",
        "model": "Civic",
        "trim": "EX",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 32,
        "highway_mpg": 42,
    },
    {
        "make": "Honda",
        "model": "Accord",
        "trim": "Sport",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 30,
        "highway_mpg": 38,
    },
    {
        "make": "Honda",
        "model": "CR-V",
        "trim": "EX",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 28,
        "highway_mpg": 34,
    },
    {
        "make": "Honda",
        "model": "Pilot",
        "trim": "EX-L",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 20,
        "highway_mpg": 27,
    },
    {
        "make": "Honda",
        "model": "HR-V",
        "trim": "Sport",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 28,
        "highway_mpg": 34,
    },

    # Ford
    {
        "make": "Ford",
        "model": "F-150",
        "trim": "XLT",
        "body_style": "Truck",
        "fuel_type": "Gasoline",
        "city_mpg": 19,
        "highway_mpg": 24,
    },
    {
        "make": "Ford",
        "model": "Escape",
        "trim": "SE",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 26,
        "highway_mpg": 31,
    },
    {
        "make": "Ford",
        "model": "Explorer",
        "trim": "XLT",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 21,
        "highway_mpg": 28,
    },
    {
        "make": "Ford",
        "model": "Mustang",
        "trim": "EcoBoost",
        "body_style": "Coupe",
        "fuel_type": "Gasoline",
        "city_mpg": 21,
        "highway_mpg": 32,
    },
    {
        "make": "Ford",
        "model": "Bronco Sport",
        "trim": "Big Bend",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 25,
        "highway_mpg": 28,
    },

    # Chevrolet
    {
        "make": "Chevrolet",
        "model": "Silverado 1500",
        "trim": "LT",
        "body_style": "Truck",
        "fuel_type": "Gasoline",
        "city_mpg": 17,
        "highway_mpg": 23,
    },
    {
        "make": "Chevrolet",
        "model": "Equinox",
        "trim": "LT",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 26,
        "highway_mpg": 31,
    },
    {
        "make": "Chevrolet",
        "model": "Tahoe",
        "trim": "LT",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 16,
        "highway_mpg": 20,
    },
    {
        "make": "Chevrolet",
        "model": "Malibu",
        "trim": "LT",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 29,
        "highway_mpg": 36,
    },
    {
        "make": "Chevrolet",
        "model": "Traverse",
        "trim": "LT Cloth",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 18,
        "highway_mpg": 27,
    },

    # Nissan
    {
        "make": "Nissan",
        "model": "Rogue",
        "trim": "SV",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 27,
        "highway_mpg": 35,
    },
    {
        "make": "Nissan",
        "model": "Altima",
        "trim": "SV",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 28,
        "highway_mpg": 39,
    },
    {
        "make": "Nissan",
        "model": "Sentra",
        "trim": "SV",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 29,
        "highway_mpg": 39,
    },
    {
        "make": "Nissan",
        "model": "Murano",
        "trim": "SL",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 20,
        "highway_mpg": 28,
    },
    {
        "make": "Nissan",
        "model": "Frontier",
        "trim": "SV",
        "body_style": "Truck",
        "fuel_type": "Gasoline",
        "city_mpg": 18,
        "highway_mpg": 24,
    },

    # Hyundai
    {
        "make": "Hyundai",
        "model": "Elantra",
        "trim": "SEL",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 31,
        "highway_mpg": 41,
    },
    {
        "make": "Hyundai",
        "model": "Sonata",
        "trim": "SEL",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 27,
        "highway_mpg": 37,
    },
    {
        "make": "Hyundai",
        "model": "Tucson",
        "trim": "SEL",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 26,
        "highway_mpg": 33,
    },
    {
        "make": "Hyundai",
        "model": "Santa Fe",
        "trim": "SEL",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 22,
        "highway_mpg": 29,
    },
    {
        "make": "Hyundai",
        "model": "Kona",
        "trim": "SEL",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 30,
        "highway_mpg": 35,
    },

    # Kia
    {
        "make": "Kia",
        "model": "Forte",
        "trim": "LXS",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 31,
        "highway_mpg": 41,
    },
    {
        "make": "Kia",
        "model": "K5",
        "trim": "LXS",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 29,
        "highway_mpg": 38,
    },
    {
        "make": "Kia",
        "model": "Sportage",
        "trim": "EX",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 25,
        "highway_mpg": 32,
    },
    {
        "make": "Kia",
        "model": "Sorento",
        "trim": "EX",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 22,
        "highway_mpg": 29,
    },
    {
        "make": "Kia",
        "model": "Telluride",
        "trim": "EX",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 20,
        "highway_mpg": 26,
    },

    # Subaru
    {
        "make": "Subaru",
        "model": "Outback",
        "trim": "Premium",
        "body_style": "Wagon",
        "fuel_type": "Gasoline",
        "city_mpg": 26,
        "highway_mpg": 33,
    },
    {
        "make": "Subaru",
        "model": "Forester",
        "trim": "Premium",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 26,
        "highway_mpg": 33,
    },
    {
        "make": "Subaru",
        "model": "Crosstrek",
        "trim": "Premium",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 27,
        "highway_mpg": 34,
    },
    {
        "make": "Subaru",
        "model": "Impreza",
        "trim": "Premium",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 28,
        "highway_mpg": 36,
    },
    {
        "make": "Subaru",
        "model": "Ascent",
        "trim": "Premium",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 21,
        "highway_mpg": 27,
    },

    # Mazda
    {
        "make": "Mazda",
        "model": "Mazda3",
        "trim": "Preferred",
        "body_style": "Hatchback",
        "fuel_type": "Gasoline",
        "city_mpg": 28,
        "highway_mpg": 36,
    },
    {
        "make": "Mazda",
        "model": "CX-5",
        "trim": "Touring",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 24,
        "highway_mpg": 31,
    },
    {
        "make": "Mazda",
        "model": "CX-30",
        "trim": "Preferred",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 25,
        "highway_mpg": 33,
    },
    {
        "make": "Mazda",
        "model": "CX-9",
        "trim": "Touring",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 20,
        "highway_mpg": 26,
    },
    {
        "make": "Mazda",
        "model": "Mazda6",
        "trim": "Touring",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 26,
        "highway_mpg": 35,
    },

    # Volkswagen
    {
        "make": "Volkswagen",
        "model": "Jetta",
        "trim": "SE",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 29,
        "highway_mpg": 40,
    },
    {
        "make": "Volkswagen",
        "model": "Golf",
        "trim": "TSI",
        "body_style": "Hatchback",
        "fuel_type": "Gasoline",
        "city_mpg": 29,
        "highway_mpg": 36,
    },
    {
        "make": "Volkswagen",
        "model": "Tiguan",
        "trim": "SE",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 23,
        "highway_mpg": 29,
    },
    {
        "make": "Volkswagen",
        "model": "Atlas",
        "trim": "SE",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 20,
        "highway_mpg": 27,
    },
    {
        "make": "Volkswagen",
        "model": "ID.4",
        "trim": "Pro",
        "body_style": "SUV",
        "fuel_type": "Electric",
        "city_mpg": None,
        "highway_mpg": None,
    },

    # BMW
    {
        "make": "BMW",
        "model": "3 Series",
        "trim": "330i",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 26,
        "highway_mpg": 36,
    },
    {
        "make": "BMW",
        "model": "5 Series",
        "trim": "530i",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 25,
        "highway_mpg": 33,
    },
    {
        "make": "BMW",
        "model": "X3",
        "trim": "xDrive30i",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 23,
        "highway_mpg": 29,
    },
    {
        "make": "BMW",
        "model": "X5",
        "trim": "xDrive40i",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 21,
        "highway_mpg": 26,
    },
    {
        "make": "BMW",
        "model": "X1",
        "trim": "xDrive28i",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 24,
        "highway_mpg": 33,
    },

    # Mercedes-Benz
    {
        "make": "Mercedes-Benz",
        "model": "C-Class",
        "trim": "C 300",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 25,
        "highway_mpg": 36,
    },
    {
        "make": "Mercedes-Benz",
        "model": "E-Class",
        "trim": "E 350",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 23,
        "highway_mpg": 32,
    },
    {
        "make": "Mercedes-Benz",
        "model": "GLC",
        "trim": "GLC 300",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 22,
        "highway_mpg": 29,
    },
    {
        "make": "Mercedes-Benz",
        "model": "GLE",
        "trim": "GLE 350",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 20,
        "highway_mpg": 27,
    },
    {
        "make": "Mercedes-Benz",
        "model": "GLA",
        "trim": "GLA 250",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 24,
        "highway_mpg": 34,
    },

    # Audi
    {
        "make": "Audi",
        "model": "A4",
        "trim": "Premium",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 24,
        "highway_mpg": 33,
    },
    {
        "make": "Audi",
        "model": "A6",
        "trim": "Premium",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 23,
        "highway_mpg": 32,
    },
    {
        "make": "Audi",
        "model": "Q5",
        "trim": "Premium",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 23,
        "highway_mpg": 28,
    },
    {
        "make": "Audi",
        "model": "Q7",
        "trim": "Premium",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 19,
        "highway_mpg": 25,
    },
    {
        "make": "Audi",
        "model": "Q3",
        "trim": "Premium",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 22,
        "highway_mpg": 30,
    },

    # Jeep
    {
        "make": "Jeep",
        "model": "Wrangler",
        "trim": "Sport",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 17,
        "highway_mpg": 25,
    },
    {
        "make": "Jeep",
        "model": "Grand Cherokee",
        "trim": "Limited",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 19,
        "highway_mpg": 26,
    },
    {
        "make": "Jeep",
        "model": "Cherokee",
        "trim": "Latitude",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 22,
        "highway_mpg": 31,
    },
    {
        "make": "Jeep",
        "model": "Compass",
        "trim": "Latitude",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 22,
        "highway_mpg": 31,
    },
    {
        "make": "Jeep",
        "model": "Renegade",
        "trim": "Latitude",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 24,
        "highway_mpg": 32,
    },

    # GMC
    {
        "make": "GMC",
        "model": "Sierra 1500",
        "trim": "SLE",
        "body_style": "Truck",
        "fuel_type": "Gasoline",
        "city_mpg": 17,
        "highway_mpg": 23,
    },
    {
        "make": "GMC",
        "model": "Terrain",
        "trim": "SLE",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 25,
        "highway_mpg": 30,
    },
    {
        "make": "GMC",
        "model": "Acadia",
        "trim": "SLE",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 19,
        "highway_mpg": 27,
    },
    {
        "make": "GMC",
        "model": "Yukon",
        "trim": "SLT",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 15,
        "highway_mpg": 20,
    },
    {
        "make": "GMC",
        "model": "Canyon",
        "trim": "SLE",
        "body_style": "Truck",
        "fuel_type": "Gasoline",
        "city_mpg": 19,
        "highway_mpg": 25,
    },

    # Ram
    {
        "make": "Ram",
        "model": "1500",
        "trim": "Big Horn",
        "body_style": "Truck",
        "fuel_type": "Gasoline",
        "city_mpg": 19,
        "highway_mpg": 24,
    },
    {
        "make": "Ram",
        "model": "2500",
        "trim": "Tradesman",
        "body_style": "Truck",
        "fuel_type": "Gasoline",
        "city_mpg": 15,
        "highway_mpg": 21,
    },
    {
        "make": "Ram",
        "model": "ProMaster City",
        "trim": "Base",
        "body_style": "Van",
        "fuel_type": "Gasoline",
        "city_mpg": 21,
        "highway_mpg": 28,
    },
    {
        "make": "Ram",
        "model": "3500",
        "trim": "Tradesman",
        "body_style": "Truck",
        "fuel_type": "Gasoline",
        "city_mpg": 14,
        "highway_mpg": 20,
    },
    {
        "make": "Ram",
        "model": "ProMaster",
        "trim": "2500",
        "body_style": "Van",
        "fuel_type": "Gasoline",
        "city_mpg": 18,
        "highway_mpg": 25,
    },

    # Lexus
    {
        "make": "Lexus",
        "model": "RX 350",
        "trim": "Base",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 20,
        "highway_mpg": 27,
    },
    {
        "make": "Lexus",
        "model": "NX 300",
        "trim": "Base",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 22,
        "highway_mpg": 28,
    },
    {
        "make": "Lexus",
        "model": "ES 350",
        "trim": "Base",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 22,
        "highway_mpg": 32,
    },
    {
        "make": "Lexus",
        "model": "IS 300",
        "trim": "Base",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 21,
        "highway_mpg": 31,
    },
    {
        "make": "Lexus",
        "model": "GX 460",
        "trim": "Base",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 15,
        "highway_mpg": 19,
    },

    # Tesla
    {
        "make": "Tesla",
        "model": "Model 3",
        "trim": "Long Range",
        "body_style": "Sedan",
        "fuel_type": "Electric",
        "city_mpg": None,
        "highway_mpg": None,
    },
    {
        "make": "Tesla",
        "model": "Model Y",
        "trim": "Long Range",
        "body_style": "SUV",
        "fuel_type": "Electric",
        "city_mpg": None,
        "highway_mpg": None,
    },
    {
        "make": "Tesla",
        "model": "Model S",
        "trim": "Long Range",
        "body_style": "Sedan",
        "fuel_type": "Electric",
        "city_mpg": None,
        "highway_mpg": None,
    },
    {
        "make": "Tesla",
        "model": "Model X",
        "trim": "Long Range",
        "body_style": "SUV",
        "fuel_type": "Electric",
        "city_mpg": None,
        "highway_mpg": None,
    },
    {
        "make": "Tesla",
        "model": "Cybertruck",
        "trim": "Dual Motor",
        "body_style": "Truck",
        "fuel_type": "Electric",
        "city_mpg": None,
        "highway_mpg": None,
    },

    # Dodge
    {
        "make": "Dodge",
        "model": "Charger",
        "trim": "SXT",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 19,
        "highway_mpg": 30,
    },
    {
        "make": "Dodge",
        "model": "Challenger",
        "trim": "SXT",
        "body_style": "Coupe",
        "fuel_type": "Gasoline",
        "city_mpg": 19,
        "highway_mpg": 30,
    },
    {
        "make": "Dodge",
        "model": "Durango",
        "trim": "GT",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 19,
        "highway_mpg": 26,
    },
    {
        "make": "Dodge",
        "model": "Journey",
        "trim": "SE",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 19,
        "highway_mpg": 25,
    },
    {
        "make": "Dodge",
        "model": "Hornet",
        "trim": "GT",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 21,
        "highway_mpg": 29,
    },

    # Volvo
    {
        "make": "Volvo",
        "model": "XC60",
        "trim": "Momentum",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 22,
        "highway_mpg": 28,
    },
    {
        "make": "Volvo",
        "model": "XC90",
        "trim": "Momentum",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 21,
        "highway_mpg": 30,
    },
    {
        "make": "Volvo",
        "model": "S60",
        "trim": "Momentum",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 23,
        "highway_mpg": 34,
    },
    {
        "make": "Volvo",
        "model": "S90",
        "trim": "Momentum",
        "body_style": "Sedan",
        "fuel_type": "Gasoline",
        "city_mpg": 23,
        "highway_mpg": 34,
    },
    {
        "make": "Volvo",
        "model": "XC40",
        "trim": "Momentum",
        "body_style": "SUV",
        "fuel_type": "Gasoline",
        "city_mpg": 23,
        "highway_mpg": 32,
    },
]


def build_demo_listings() -> List[Dict[str, Any]]:
    listings: List[Dict[str, Any]] = []
    for idx, spec in enumerate(SAMPLE_LISTINGS, start=1):
        year = 2016 + (idx % 9)  # spreads between 2016 and 2024
        base_price = 18000 + (year - 2016) * 1500
        price = base_price + (idx % 6) * 700
        mileage = 15000 + idx * 320
        distance_miles = 5 + (idx * 9) % 180
        safety_rating = 5 if idx % 7 != 0 else 4

        listings.append(
            {
                "id": f"d{idx}",
                "year": year,
                "make": spec["make"],
                "model": spec["model"],
                "trim": spec["trim"],
                "price": price,
                "mileage": mileage,
                "distance_miles": distance_miles,
                "fuel_type": spec["fuel_type"],
                "body_style": spec["body_style"],
                "city_mpg": spec["city_mpg"],
                "highway_mpg": spec["highway_mpg"],
                "safety_rating": safety_rating,
                "source": "demo",
            }
        )
    return listings


EXTRA_SAMPLE_LISTINGS: List[Dict[str, Any]] = build_demo_listings()

# If you want everything in one list alongside your originals

SAMPLE_LISTINGS.extend(EXTRA_SAMPLE_LISTINGS)
