"""Sample in-memory car listings for demo scoring/search."""
from typing import List, Dict, Any

SAMPLE_LISTINGS: List[Dict[str, Any]] = [
    {
        "id": "a1",
        "year": 2019,
        "make": "Honda",
        "model": "CR-V",
        "trim": "EX-L",
        "price": 23800,
        "mileage": 41000,
        "distance_miles": 22,
        "fuel_type": "Gasoline",
        "body_style": "SUV",
        "city_mpg": 28,
        "highway_mpg": 34,
        "safety_rating": 5,
        "source": "demo",
    },
    {
        "id": "a2",
        "year": 2021,
        "make": "Toyota",
        "model": "Camry",
        "trim": "Hybrid LE",
        "price": 25500,
        "mileage": 29000,
        "distance_miles": 48,
        "fuel_type": "Hybrid",
        "body_style": "Sedan",
        "city_mpg": 51,
        "highway_mpg": 53,
        "safety_rating": 5,
        "source": "demo",
    },
    {
        "id": "a3",
        "year": 2018,
        "make": "Subaru",
        "model": "Outback",
        "trim": "Premium",
        "price": 19500,
        "mileage": 72000,
        "distance_miles": 15,
        "fuel_type": "Gasoline",
        "body_style": "Wagon",
        "city_mpg": 25,
        "highway_mpg": 32,
        "safety_rating": 5,
        "source": "demo",
    },
    {
        "id": "a4",
        "year": 2020,
        "make": "Tesla",
        "model": "Model 3",
        "trim": "Standard Range Plus",
        "price": 30900,
        "mileage": 28000,
        "distance_miles": 75,
        "fuel_type": "Electric",
        "body_style": "Sedan",
        "city_mpg": None,
        "highway_mpg": None,
        "safety_rating": 5,
        "source": "demo",
    },
    {
        "id": "a5",
        "year": 2017,
        "make": "Ford",
        "model": "F-150",
        "trim": "XLT",
        "price": 22400,
        "mileage": 91000,
        "distance_miles": 110,
        "fuel_type": "Gasoline",
        "body_style": "Truck",
        "city_mpg": 19,
        "highway_mpg": 25,
        "safety_rating": 4,
        "source": "demo",
    },
]